### ISSUE TITLE
transformerInterface thumbnail generation

### ISSUE THREAD

**Issue by KingLoui** [josegonzalez/cakephp-upload#368]
I just tried implementing your tutorial from here and ran into a few issues. 
First I copied this codeblock from the tutorial:

```
'transformer' => function (Table $table, Entity $entity, $data, $field, $settings) {
            // Store the thumbnail in a temporary file
            $tmp = tmpfile();
            // Use the Imagine library to DO THE THING
            $size = new \Imagine\Image\Box(40, 40);
            $mode = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;
            $imagine = new \Imagine\Gd\Imagine();
            // Save that modified file to our temp file
            $imagine->open($data['tmp_name'])
                    ->thumbnail($size, $mode)
                    ->save($tmp);
            // Now return the original *and* the thumbnail
            return [
                $data['tmp_name'] => $data['name'],
                $tmp => 'thumbnail-' . $data['name'],
            ];
        },
```

the first issue I ran into was that the behavior fires an error because it expects a class instead it gets a closure. i fixed that by implementing the transformerInterface and copying the code into the transform function of said implementation.

The next issue is that tmpfile() returns a resource handle but $imagine->save() expects a filepath. The return statement uses that tmpfile() handle as a key which fires an error as well.
When I try passing the filepath of that tempfile instead of the handle the tmpfile gets deleted before the save function picks it up.
Imagine also fires an error because in the save function theres no file extention specified, but doing so didn't solve my problem.

I got it fixed by letting imagine write a new file but that one doesn't get deleted automagically.

Can somebody point me directions?
I'm sure there is an easy fix for this but I am relatively new to CakePHP.

**Comment by josegonzalez** [comment]
What version of the plugin did you install? I added the ability to use a callback in 3.0.3.

**Comment by KingLoui** [comment]
I'm using 3.0.0, I will look into that callback but nonetheless I'm wondering how that code i posted worked in the first place because it isn't that dated?

**Comment by josegonzalez** [comment]
I released my 3.0.3 version in response to the blog post, to make the blog post version simpler. Can you try upgrading to the latest version of the plugin (3.2 I think) and see if it works? I dropped php 5.4 support in 3.1.0, but hopefully that doesn't affect you.

**Comment by KingLoui** [comment]
I just updated to 3.2.0 but I cant find a clue on how to implement a callback in my TransformerClass.
Out of curiosity i tried again with the code from the blogpost which i posted in the first post but it still shows the following error

..

now I'm stuck at this point in my ThumbnailTransformer Class
```
public function transform()
{
    $handle = tmpfile();
    $path = stream_get_meta_data($handle)['uri'];
    // Use the Imagine library to DO THE THING
    $size = new \Imagine\Image\Box(40, 40);
    $mode = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;
    $imagine = new \Imagine\Gd\Imagine();
    // Save that modified file to our temp file
    $imagine->open($this->data['tmp_name'])
            ->thumbnail($size, $mode)
            ->save($path, ['format' => 'jpeg']);
    // Now return the original *and* the thumbnail
    return [
        $this->data['tmp_name'] => $this->data['name'],
        $path => 'thumbnail-' . $this->data['name'],
    ];
}
```
I retrieved the filepath from that tmpfile and passed it to imagines save and added the file extension but i think when the uploadplugin saves, the tmpfile got already deleted because theres no handle left in memory.
My question is how can I set that callback so the handle lives long enough for, so the plugin can save that file?
Thank you very much for your effort so far!

**Comment by KingLoui** [comment]
I can't find the place where you defined the callback in the source of your plugin. If I investigated correctly you added the ability to pass a callable as a transformer, but that is not my main issue.
I just wanted to know how I solve my problem with the tmpfile, because if I use a tmpfile it gets deleted before the plugin can save it to the final destination. If I don't use a tmpfile I can't delete the generated temporary thumbnail because there is no afterSave hook..
I hope you understand what I am meaning, I'm having a hard time describing this issue.

Thanks a lot again!

**Comment by josegonzalez** [comment]
I sat down and looked at my tutorial. I guess when writing it, I refactored things I should not have. The newest version should have *exactly* what is needed, and I tested it out locally.

- Extracted the extension using `pathinfo`. Imagine barfs otherwise, oops.
- Use `tempnam` instead of `tmpfile` to get the name of the temporary file. This seems to fix uploads nicely.
- Updated the callback signature to use the fully-namespaced class names. This might fix any lingering issues you have.

You should be able to make the above changes to my original tutorial and get everything working. I've also updated the tutorial itself with better step-by-step instructions. Let me know if that helps.

**Comment by KingLoui** [comment]
I just tried with your updated example code, before i had a similar solution also using tempnam, though there are still two issues.

1. tempnam creates a tmp file without extension but you save the output of imagine to the tempnam file name + extension so if you check your tmpdir manually you will have 2 files, a 0 byte tmp file created by tempnam and the file containing the image.

2. Both files mentioned in 1. won't get automatically deleted and will stay in the tmpdir forever so for every upload i get an overhead of 2 files in my tmpdir.

Im looking for a solution on how to delete these tmpfiles after the upload plugin has saved them.

**Comment by josegonzalez** [comment]
I suppose thats a good point. We can probably immediately delete `$tmp`, as all we really want is a temp path. I'll fix that in my tutorial.

For the second issue, we can probably have another method that post-processes a file after the files have been written to their correct locations. By default we could just delete them, though in theory you could do any number of other things.

I normally just have a crontask that deletes old files in temp :)

Thoughts?

**Comment by KingLoui** [comment]
> For the second issue, we can probably have another method that post-processes a file after the files have been written to their correct locations. By default we could just delete them, though in theory you could do any number of other things.

that sounds like the most elegant way, I think a cronjob is a little overkill for that purpose.
I think I won't be able to implement that post processor up to your plugin standards because I'm still a learner and haven't mastered phpunit yet but i will try.

Maybe you can give me a little feedback on how i would approach this.
My idea is to update the DefaultWriter's write method and call a post process method from there.

**Comment by josegonzalez** [comment]
That works for me :)
